name: Cleanup Firebase Salas

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run cleanup script
        run: node cleanUp.js
        env:
          FIREBASE_CONFIG_JSON_BASE64: ${{ secrets.FIREBASE_CONFIG_JSON_BASE64 }}

      - name: Confirmación visual
        run: echo "✅ Limpieza completada"

      - name: Notificar éxito por issue
        if: ${{ success() }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "✅ Limpieza de Firebase exitosa",
              "body": "@jgarcia311999 la limpieza de Firebase se ejecutó correctamente 🧹",
              "labels": ["notificación"]
            }'

      - name: Notificar error por issue
        if: ${{ failure() }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{
              "title": "❌ Error en limpieza de Firebase",
              "body": "Hola @jgarcia311999, la acción de limpieza falló en `${{ github.ref }}`. Revisa los logs del workflow para más detalles.",
              "labels": ["error", "notificación"]
            }'